### ISSUE TITLE
Full of bugs that may or may not be related to one bug...

### ISSUE THREAD

**Issue by Core2Quad-779** [Anonymous941/3DS-Chunker#5]
...but either way, I tried running it with a folder titled "cgQAAGM0BAA=" and got a whole bunch of issues in return:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\Scripts\3dschunker.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\click\core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mc3ds\__main__.py", line 86, in main
    convert(world, blank_world, world_out, delete_out)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mc3ds\convert.py", line 164, in convert
    shutil.copytree(blank_world, world_out)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 591, in copytree
    with os.scandir(src) as itr:
         ~~~~~~~~~~^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\samue\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\blankworld'`

And I have no clue how to get it working.

**Comment by Anonymous941** [comment]
This was a simple mistake I made, sorry about that.  I think I fixed it, please run `pip install --upgrade git+https://github.com/MC3DS-Save-Research/3DS-Chunker` and try again

**Comment by Core2Quad-779** [comment]
Thanks, and nice to see this project is still active! (I've come across a lot of GitHub projects with good intentions that are just no longer active.)

**Comment by Core2Quad-779** [comment]
It's still broken.

I tried both updating and reinstalling it, got this error anyway:

`File "/Library/Frameworks/Python.framework/Versions/3.12/bin/3dschunker", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mc3ds/__main__.py", line 86, in main
    convert(world, blank_world, world_out, delete_out)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mc3ds/convert.py", line 164, in convert
    shutil.copytree(blank_world, world_out)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py", line 586, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/blankworld'`

**Comment by Core2Quad-779** [comment]
If the fact that I tried this in MacOS doesn't sit well with you, well don't worry. It's broken in Windows too.

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\Scripts\3dschunker.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\click\core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mc3ds\__main__.py", line 86, in main
    convert(world, blank_world, world_out, delete_out)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samue\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\mc3ds\convert.py", line 164, in convert
    shutil.copytree(blank_world, world_out)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 591, in copytree
    with os.scandir(src) as itr:
         ~~~~~~~~~~^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\samue\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\blankworld'`

**Comment by Anonymous941** [comment]
> Thanks, and nice to see this project is still active! (I've come across a lot of GitHub projects with good intentions that are just no longer active.)

Yeah I have too, it's certainly annoying especially when there are no alternatives

> If the fact that I tried this in MacOS doesn't sit well with you, well don't worry. It's broken in Windows too.

macOS is fine, this was another bug in accessing my script's resources.  99% of the time, it's my fault when there are errors in this program, don't worry :)

Try updating again.  If you get the same error, you can try downloading the folder manually: go to https://download-directory.github.io/, and extract the zip to the path mentioned at the end of the error messages (I can give more instructions if you want)

**Comment by Core2Quad-779** [comment]
> Yeah I have too, it's certainly annoying especially when there are no alternatives

Or (in this case) are alternatives, but are in development/even worse.

> If you get the same error, you can try downloading the folder manually: go to https://download-directory.github.io/, and extract the zip to the path mentioned at the end of the error messages (I can give more instructions if you want)

Thanks a lot, that worked for me!

**Comment by Core2Quad-779** [comment]
Reopened the issue because I’m using it wrong. Sorry!

**Comment by Anonymous941** [comment]
> Or (in this case) are alternatives, but are in development/even worse.

Which ones?  I didn't know there were any other 3DS to Java converters

> Reopened the issue because I’m using it wrong. Sorry!

No problem, glad it works

**Comment by Core2Quad-779** [comment]
> Which ones? I didn't know there were any other 3DS to Java converters

Project Lodestone is essentially the "everything" Minecraft world converter, and it supports MC:N3DSE, but it's still in development.

**Comment by Anonymous941** [comment]
Ah okay, I just started working on it with them on Discord a couple days ago.  So hopefully it will be ready soon, it's probably going to be much more reliable then mine
